/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "SmartCampusAcademicPlus",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartCampusAcademicPlus__factory>;
    getContractFactory(
      name: "SmartCampusAdmission",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartCampusAdmission__factory>;
    getContractFactory(
      name: "SmartCampusCampusLife",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartCampusCampusLife__factory>;
    getContractFactory(
      name: "SmartCampusComplaints",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartCampusComplaints__factory>;
    getContractFactory(
      name: "SmartCampusEquity",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartCampusEquity__factory>;
    getContractFactory(
      name: "SmartCampusFinance",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartCampusFinance__factory>;
    getContractFactory(
      name: "SmartCampusGovernance",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartCampusGovernance__factory>;
    getContractFactory(
      name: "SmartCampusHiring",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartCampusHiring__factory>;
    getContractFactory(
      name: "SmartCampusIdentity",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartCampusIdentity__factory>;
    getContractFactory(
      name: "SmartCampusLearning",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartCampusLearning__factory>;
    getContractFactory(
      name: "SmartCampusLibrary",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartCampusLibrary__factory>;
    getContractFactory(
      name: "SmartCampusReevaluation",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartCampusReevaluation__factory>;
    getContractFactory(
      name: "SmartCampusVerify",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartCampusVerify__factory>;
    getContractFactory(
      name: "SmartCampusWorkplace",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SmartCampusWorkplace__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "SmartCampusAcademicPlus",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartCampusAcademicPlus>;
    getContractAt(
      name: "SmartCampusAdmission",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartCampusAdmission>;
    getContractAt(
      name: "SmartCampusCampusLife",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartCampusCampusLife>;
    getContractAt(
      name: "SmartCampusComplaints",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartCampusComplaints>;
    getContractAt(
      name: "SmartCampusEquity",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartCampusEquity>;
    getContractAt(
      name: "SmartCampusFinance",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartCampusFinance>;
    getContractAt(
      name: "SmartCampusGovernance",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartCampusGovernance>;
    getContractAt(
      name: "SmartCampusHiring",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartCampusHiring>;
    getContractAt(
      name: "SmartCampusIdentity",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartCampusIdentity>;
    getContractAt(
      name: "SmartCampusLearning",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartCampusLearning>;
    getContractAt(
      name: "SmartCampusLibrary",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartCampusLibrary>;
    getContractAt(
      name: "SmartCampusReevaluation",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartCampusReevaluation>;
    getContractAt(
      name: "SmartCampusVerify",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartCampusVerify>;
    getContractAt(
      name: "SmartCampusWorkplace",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SmartCampusWorkplace>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "SmartCampusAcademicPlus",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusAcademicPlus>;
    deployContract(
      name: "SmartCampusAdmission",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusAdmission>;
    deployContract(
      name: "SmartCampusCampusLife",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusCampusLife>;
    deployContract(
      name: "SmartCampusComplaints",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusComplaints>;
    deployContract(
      name: "SmartCampusEquity",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusEquity>;
    deployContract(
      name: "SmartCampusFinance",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusFinance>;
    deployContract(
      name: "SmartCampusGovernance",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusGovernance>;
    deployContract(
      name: "SmartCampusHiring",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusHiring>;
    deployContract(
      name: "SmartCampusIdentity",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusIdentity>;
    deployContract(
      name: "SmartCampusLearning",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusLearning>;
    deployContract(
      name: "SmartCampusLibrary",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusLibrary>;
    deployContract(
      name: "SmartCampusReevaluation",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusReevaluation>;
    deployContract(
      name: "SmartCampusVerify",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusVerify>;
    deployContract(
      name: "SmartCampusWorkplace",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusWorkplace>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "SmartCampusAcademicPlus",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusAcademicPlus>;
    deployContract(
      name: "SmartCampusAdmission",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusAdmission>;
    deployContract(
      name: "SmartCampusCampusLife",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusCampusLife>;
    deployContract(
      name: "SmartCampusComplaints",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusComplaints>;
    deployContract(
      name: "SmartCampusEquity",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusEquity>;
    deployContract(
      name: "SmartCampusFinance",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusFinance>;
    deployContract(
      name: "SmartCampusGovernance",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusGovernance>;
    deployContract(
      name: "SmartCampusHiring",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusHiring>;
    deployContract(
      name: "SmartCampusIdentity",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusIdentity>;
    deployContract(
      name: "SmartCampusLearning",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusLearning>;
    deployContract(
      name: "SmartCampusLibrary",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusLibrary>;
    deployContract(
      name: "SmartCampusReevaluation",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusReevaluation>;
    deployContract(
      name: "SmartCampusVerify",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusVerify>;
    deployContract(
      name: "SmartCampusWorkplace",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SmartCampusWorkplace>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
