/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { SmartCampusAcademicPlus } from "./contracts/SmartCampusAcademicPlus";
export { SmartCampusAcademicPlus__factory } from "./factories/contracts/SmartCampusAcademicPlus__factory";
export type { SmartCampusAdmission } from "./contracts/SmartCampusAdmission";
export { SmartCampusAdmission__factory } from "./factories/contracts/SmartCampusAdmission__factory";
export type { SmartCampusCampusLife } from "./contracts/SmartCampusCampusLife";
export { SmartCampusCampusLife__factory } from "./factories/contracts/SmartCampusCampusLife__factory";
export type { SmartCampusComplaints } from "./contracts/SmartCampusComplaints";
export { SmartCampusComplaints__factory } from "./factories/contracts/SmartCampusComplaints__factory";
export type { SmartCampusEquity } from "./contracts/SmartCampusEquity";
export { SmartCampusEquity__factory } from "./factories/contracts/SmartCampusEquity__factory";
export type { SmartCampusFinance } from "./contracts/SmartCampusFinance";
export { SmartCampusFinance__factory } from "./factories/contracts/SmartCampusFinance__factory";
export type { SmartCampusGovernance } from "./contracts/SmartCampusGovernance";
export { SmartCampusGovernance__factory } from "./factories/contracts/SmartCampusGovernance__factory";
export type { SmartCampusHiring } from "./contracts/SmartCampusHiring";
export { SmartCampusHiring__factory } from "./factories/contracts/SmartCampusHiring__factory";
export type { SmartCampusIdentity } from "./contracts/SmartCampusIdentity";
export { SmartCampusIdentity__factory } from "./factories/contracts/SmartCampusIdentity__factory";
export type { SmartCampusLearning } from "./contracts/SmartCampusLearning";
export { SmartCampusLearning__factory } from "./factories/contracts/SmartCampusLearning__factory";
export type { SmartCampusLibrary } from "./contracts/SmartCampusLibrary";
export { SmartCampusLibrary__factory } from "./factories/contracts/SmartCampusLibrary__factory";
export type { SmartCampusReevaluation } from "./contracts/SmartCampusReevaluation";
export { SmartCampusReevaluation__factory } from "./factories/contracts/SmartCampusReevaluation__factory";
export type { SmartCampusVerify } from "./contracts/SmartCampusVerify";
export { SmartCampusVerify__factory } from "./factories/contracts/SmartCampusVerify__factory";
export type { SmartCampusWorkplace } from "./contracts/SmartCampusWorkplace";
export { SmartCampusWorkplace__factory } from "./factories/contracts/SmartCampusWorkplace__factory";
