import { useEffect } from 'react';
import { io, Socket } from 'socket.io-client';
import { useAuthStore } from '@/lib/store/useAuthStore';
import { useRouter } from 'next/navigation';
import Cookies from 'js-cookie';

export const useRealtimeUpdates = () => {
    const { user } = useAuthStore();
    const router = useRouter();

    useEffect(() => {
        const token = Cookies.get('token');
        if (!token || !user) return;

        // Initialize Socket connection
        const socket: Socket = io(`${process.env.NEXT_PUBLIC_SOCKET_URL || 'http://localhost:8000'}/timetables`, {
            auth: { token }
        });

        socket.on('connect', () => {
            console.log('Real-time connection established.');
        });

        // Event for Department Admins when their master timetable is generated
        socket.on('timetable:generated', (data: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
            console.log('Timetable Generated Event Received:', data);

            // Dispatch a custom event that specific pages can listen to for softer refetches
            window.dispatchEvent(new CustomEvent('timetable:generated', { detail: data }));

            // Display an alert (In production, replace with shadcn/ui toast)
            alert(`New Timetable Matrix Generated! (Generation Time: ${data.generationMs}ms)${data.isSpecial ? ' [EMERGENCY SUBSTITUTION APPLIED]' : ''}`);

            // Force a hard router refresh to pick up the new server payloads gracefully
            router.refresh();
        });

        // Event for Faculty when their personal nested schedule updates
        socket.on('schedule:updated', (data: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
            console.log('Faculty Schedule Updated Event Received:', data);

            window.dispatchEvent(new CustomEvent('schedule:updated', { detail: data }));

            // Display an alert
            alert(`A new Master Schedule was generated by the department. Your Personal Timetable has been refreshed.`);

            // Force refresh 
            router.refresh();
        });

        socket.on('connect_error', (err) => {
            console.error('Socket Connection Error:', err.message);
        });

        return () => {
            socket.disconnect();
        };
    }, [user, router]);
};
