/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SmartCampusAcademicPlus } from "./SmartCampusAcademicPlus";
export type { SmartCampusAdmission } from "./SmartCampusAdmission";
export type { SmartCampusCampusLife } from "./SmartCampusCampusLife";
export type { SmartCampusComplaints } from "./SmartCampusComplaints";
export type { SmartCampusEquity } from "./SmartCampusEquity";
export type { SmartCampusFinance } from "./SmartCampusFinance";
export type { SmartCampusGovernance } from "./SmartCampusGovernance";
export type { SmartCampusHiring } from "./SmartCampusHiring";
export type { SmartCampusIdentity } from "./SmartCampusIdentity";
export type { SmartCampusLearning } from "./SmartCampusLearning";
export type { SmartCampusLibrary } from "./SmartCampusLibrary";
export type { SmartCampusReevaluation } from "./SmartCampusReevaluation";
export type { SmartCampusVerify } from "./SmartCampusVerify";
export type { SmartCampusWorkplace } from "./SmartCampusWorkplace";
