/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartCampusIdentityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "distributeTournamentPrize"
      | "fundTournament"
      | "grantAccess"
      | "hasAccess"
      | "identities"
      | "owner"
      | "permissions"
      | "renounceOwnership"
      | "tournamentPrizes"
      | "transferOwnership"
      | "verifyKYC"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "KYCVerified"
      | "OwnershipTransferred"
      | "TournamentFunded"
      | "TournamentPrizeDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "distributeTournamentPrize",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fundTournament",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "identities",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "permissions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tournamentPrizes",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyKYC",
    values: [AddressLike, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "distributeTournamentPrize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "identities", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "permissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tournamentPrizes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyKYC", data: BytesLike): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    user: AddressLike,
    resourceId: string,
    expiry: BigNumberish
  ];
  export type OutputTuple = [user: string, resourceId: string, expiry: bigint];
  export interface OutputObject {
    user: string;
    resourceId: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCVerifiedEvent {
  export type InputTuple = [user: AddressLike, kycHash: string];
  export type OutputTuple = [user: string, kycHash: string];
  export interface OutputObject {
    user: string;
    kycHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentFundedEvent {
  export type InputTuple = [tournamentId: string, amount: BigNumberish];
  export type OutputTuple = [tournamentId: string, amount: bigint];
  export interface OutputObject {
    tournamentId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentPrizeDistributedEvent {
  export type InputTuple = [
    tournamentId: string,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: string,
    winner: string,
    amount: bigint
  ];
  export interface OutputObject {
    tournamentId: string;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartCampusIdentity extends BaseContract {
  connect(runner?: ContractRunner | null): SmartCampusIdentity;
  waitForDeployment(): Promise<this>;

  interface: SmartCampusIdentityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  distributeTournamentPrize: TypedContractMethod<
    [tournamentId: string, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  fundTournament: TypedContractMethod<
    [tournamentId: string],
    [void],
    "payable"
  >;

  grantAccess: TypedContractMethod<
    [user: AddressLike, resourceId: string, duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  hasAccess: TypedContractMethod<
    [user: AddressLike, resourceId: string],
    [boolean],
    "view"
  >;

  identities: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint] & {
        userId: string;
        kycHash: string;
        verifiedAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  permissions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint] & {
        user: string;
        resourceId: string;
        expiry: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  tournamentPrizes: TypedContractMethod<[arg0: string], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyKYC: TypedContractMethod<
    [user: AddressLike, userId: string, kycHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "distributeTournamentPrize"
  ): TypedContractMethod<
    [tournamentId: string, winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundTournament"
  ): TypedContractMethod<[tournamentId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [user: AddressLike, resourceId: string, duration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<
    [user: AddressLike, resourceId: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "identities"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint] & {
        userId: string;
        kycHash: string;
        verifiedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "permissions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint] & {
        user: string;
        resourceId: string;
        expiry: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tournamentPrizes"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyKYC"
  ): TypedContractMethod<
    [user: AddressLike, userId: string, kycHash: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "KYCVerified"
  ): TypedContractEvent<
    KYCVerifiedEvent.InputTuple,
    KYCVerifiedEvent.OutputTuple,
    KYCVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TournamentFunded"
  ): TypedContractEvent<
    TournamentFundedEvent.InputTuple,
    TournamentFundedEvent.OutputTuple,
    TournamentFundedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentPrizeDistributed"
  ): TypedContractEvent<
    TournamentPrizeDistributedEvent.InputTuple,
    TournamentPrizeDistributedEvent.OutputTuple,
    TournamentPrizeDistributedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(address,string,uint256)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "KYCVerified(address,string)": TypedContractEvent<
      KYCVerifiedEvent.InputTuple,
      KYCVerifiedEvent.OutputTuple,
      KYCVerifiedEvent.OutputObject
    >;
    KYCVerified: TypedContractEvent<
      KYCVerifiedEvent.InputTuple,
      KYCVerifiedEvent.OutputTuple,
      KYCVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TournamentFunded(string,uint256)": TypedContractEvent<
      TournamentFundedEvent.InputTuple,
      TournamentFundedEvent.OutputTuple,
      TournamentFundedEvent.OutputObject
    >;
    TournamentFunded: TypedContractEvent<
      TournamentFundedEvent.InputTuple,
      TournamentFundedEvent.OutputTuple,
      TournamentFundedEvent.OutputObject
    >;

    "TournamentPrizeDistributed(string,address,uint256)": TypedContractEvent<
      TournamentPrizeDistributedEvent.InputTuple,
      TournamentPrizeDistributedEvent.OutputTuple,
      TournamentPrizeDistributedEvent.OutputObject
    >;
    TournamentPrizeDistributed: TypedContractEvent<
      TournamentPrizeDistributedEvent.InputTuple,
      TournamentPrizeDistributedEvent.OutputTuple,
      TournamentPrizeDistributedEvent.OutputObject
    >;
  };
}
