/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartCampusWorkplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "completeInternship"
      | "internships"
      | "jobs"
      | "owner"
      | "postJob"
      | "registerInternship"
      | "releaseBonus"
      | "releaseJobPayment"
      | "renounceOwnership"
      | "transferOwnership"
      | "verifiedSkills"
      | "verifySkill"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InternshipCompleted"
      | "JobEscrowed"
      | "JobPaymentReleased"
      | "OwnershipTransferred"
      | "SalaryBonusReleased"
      | "SkillVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "completeInternship",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "internships", values: [string]): string;
  encodeFunctionData(functionFragment: "jobs", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "postJob", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerInternship",
    values: [string, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseBonus",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseJobPayment",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedSkills",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySkill",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "completeInternship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "internships",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerInternship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseJobPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedSkills",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySkill",
    data: BytesLike
  ): Result;
}

export namespace InternshipCompletedEvent {
  export type InputTuple = [
    internshipId: string,
    student: AddressLike,
    certificateHash: string
  ];
  export type OutputTuple = [
    internshipId: string,
    student: string,
    certificateHash: string
  ];
  export interface OutputObject {
    internshipId: string;
    student: string;
    certificateHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobEscrowedEvent {
  export type InputTuple = [jobId: string, amount: BigNumberish];
  export type OutputTuple = [jobId: string, amount: bigint];
  export interface OutputObject {
    jobId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobPaymentReleasedEvent {
  export type InputTuple = [
    jobId: string,
    freelancer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [jobId: string, freelancer: string, amount: bigint];
  export interface OutputObject {
    jobId: string;
    freelancer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalaryBonusReleasedEvent {
  export type InputTuple = [
    faculty: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [faculty: string, amount: bigint, reason: string];
  export interface OutputObject {
    faculty: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SkillVerifiedEvent {
  export type InputTuple = [student: AddressLike, skillBadge: string];
  export type OutputTuple = [student: string, skillBadge: string];
  export interface OutputObject {
    student: string;
    skillBadge: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartCampusWorkplace extends BaseContract {
  connect(runner?: ContractRunner | null): SmartCampusWorkplace;
  waitForDeployment(): Promise<this>;

  interface: SmartCampusWorkplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  completeInternship: TypedContractMethod<
    [internshipId: string, certificateHash: string],
    [void],
    "nonpayable"
  >;

  internships: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean, string] & {
        internshipId: string;
        student: string;
        company: string;
        completed: boolean;
        certificateHash: string;
      }
    ],
    "view"
  >;

  jobs: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean, boolean] & {
        jobId: string;
        employer: string;
        budget: bigint;
        isEscrowed: boolean;
        isCompleted: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  postJob: TypedContractMethod<[jobId: string], [void], "payable">;

  registerInternship: TypedContractMethod<
    [internshipId: string, student: AddressLike, company: string],
    [void],
    "nonpayable"
  >;

  releaseBonus: TypedContractMethod<
    [faculty: AddressLike, reason: string],
    [void],
    "payable"
  >;

  releaseJobPayment: TypedContractMethod<
    [jobId: string, freelancer: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifiedSkills: TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [boolean],
    "view"
  >;

  verifySkill: TypedContractMethod<
    [student: AddressLike, skillBadge: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "completeInternship"
  ): TypedContractMethod<
    [internshipId: string, certificateHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "internships"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean, string] & {
        internshipId: string;
        student: string;
        company: string;
        completed: boolean;
        certificateHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean, boolean] & {
        jobId: string;
        employer: string;
        budget: bigint;
        isEscrowed: boolean;
        isCompleted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postJob"
  ): TypedContractMethod<[jobId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "registerInternship"
  ): TypedContractMethod<
    [internshipId: string, student: AddressLike, company: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseBonus"
  ): TypedContractMethod<
    [faculty: AddressLike, reason: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "releaseJobPayment"
  ): TypedContractMethod<
    [jobId: string, freelancer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifiedSkills"
  ): TypedContractMethod<[arg0: AddressLike, arg1: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifySkill"
  ): TypedContractMethod<
    [student: AddressLike, skillBadge: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "InternshipCompleted"
  ): TypedContractEvent<
    InternshipCompletedEvent.InputTuple,
    InternshipCompletedEvent.OutputTuple,
    InternshipCompletedEvent.OutputObject
  >;
  getEvent(
    key: "JobEscrowed"
  ): TypedContractEvent<
    JobEscrowedEvent.InputTuple,
    JobEscrowedEvent.OutputTuple,
    JobEscrowedEvent.OutputObject
  >;
  getEvent(
    key: "JobPaymentReleased"
  ): TypedContractEvent<
    JobPaymentReleasedEvent.InputTuple,
    JobPaymentReleasedEvent.OutputTuple,
    JobPaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SalaryBonusReleased"
  ): TypedContractEvent<
    SalaryBonusReleasedEvent.InputTuple,
    SalaryBonusReleasedEvent.OutputTuple,
    SalaryBonusReleasedEvent.OutputObject
  >;
  getEvent(
    key: "SkillVerified"
  ): TypedContractEvent<
    SkillVerifiedEvent.InputTuple,
    SkillVerifiedEvent.OutputTuple,
    SkillVerifiedEvent.OutputObject
  >;

  filters: {
    "InternshipCompleted(string,address,string)": TypedContractEvent<
      InternshipCompletedEvent.InputTuple,
      InternshipCompletedEvent.OutputTuple,
      InternshipCompletedEvent.OutputObject
    >;
    InternshipCompleted: TypedContractEvent<
      InternshipCompletedEvent.InputTuple,
      InternshipCompletedEvent.OutputTuple,
      InternshipCompletedEvent.OutputObject
    >;

    "JobEscrowed(string,uint256)": TypedContractEvent<
      JobEscrowedEvent.InputTuple,
      JobEscrowedEvent.OutputTuple,
      JobEscrowedEvent.OutputObject
    >;
    JobEscrowed: TypedContractEvent<
      JobEscrowedEvent.InputTuple,
      JobEscrowedEvent.OutputTuple,
      JobEscrowedEvent.OutputObject
    >;

    "JobPaymentReleased(string,address,uint256)": TypedContractEvent<
      JobPaymentReleasedEvent.InputTuple,
      JobPaymentReleasedEvent.OutputTuple,
      JobPaymentReleasedEvent.OutputObject
    >;
    JobPaymentReleased: TypedContractEvent<
      JobPaymentReleasedEvent.InputTuple,
      JobPaymentReleasedEvent.OutputTuple,
      JobPaymentReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SalaryBonusReleased(address,uint256,string)": TypedContractEvent<
      SalaryBonusReleasedEvent.InputTuple,
      SalaryBonusReleasedEvent.OutputTuple,
      SalaryBonusReleasedEvent.OutputObject
    >;
    SalaryBonusReleased: TypedContractEvent<
      SalaryBonusReleasedEvent.InputTuple,
      SalaryBonusReleasedEvent.OutputTuple,
      SalaryBonusReleasedEvent.OutputObject
    >;

    "SkillVerified(address,string)": TypedContractEvent<
      SkillVerifiedEvent.InputTuple,
      SkillVerifiedEvent.OutputTuple,
      SkillVerifiedEvent.OutputObject
    >;
    SkillVerified: TypedContractEvent<
      SkillVerifiedEvent.InputTuple,
      SkillVerifiedEvent.OutputTuple,
      SkillVerifiedEvent.OutputObject
    >;
  };
}
