/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartCampusHiringInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOffer"
      | "getPlacement"
      | "jobListings"
      | "nextJobId"
      | "owner"
      | "placementOffers"
      | "postJob"
      | "recordPlacement"
      | "renounceOwnership"
      | "toggleJobStatus"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "JobPosted"
      | "JobStatusChanged"
      | "OfferAccepted"
      | "OwnershipTransferred"
      | "PlacementRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOffer",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlacement",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "jobListings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nextJobId", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placementOffers",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "postJob",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPlacement",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toggleJobStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlacement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "jobListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextJobId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "placementOffers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "postJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordPlacement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleJobStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace JobPostedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    institutionalId: string,
    jobTitle: string,
    companyName: string
  ];
  export type OutputTuple = [
    jobId: bigint,
    institutionalId: string,
    jobTitle: string,
    companyName: string
  ];
  export interface OutputObject {
    jobId: bigint;
    institutionalId: string;
    jobTitle: string;
    companyName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobStatusChangedEvent {
  export type InputTuple = [jobId: BigNumberish, isActive: boolean];
  export type OutputTuple = [jobId: bigint, isActive: boolean];
  export interface OutputObject {
    jobId: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferAcceptedEvent {
  export type InputTuple = [studentEnrollment: string, jobListingId: string];
  export type OutputTuple = [studentEnrollment: string, jobListingId: string];
  export interface OutputObject {
    studentEnrollment: string;
    jobListingId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlacementRecordedEvent {
  export type InputTuple = [
    studentEnrollment: string,
    jobListingId: string,
    offerHash: string
  ];
  export type OutputTuple = [
    studentEnrollment: string,
    jobListingId: string,
    offerHash: string
  ];
  export interface OutputObject {
    studentEnrollment: string;
    jobListingId: string;
    offerHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartCampusHiring extends BaseContract {
  connect(runner?: ContractRunner | null): SmartCampusHiring;
  waitForDeployment(): Promise<this>;

  interface: SmartCampusHiringInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOffer: TypedContractMethod<
    [_studentEnrollment: string, _jobListingId: string],
    [void],
    "nonpayable"
  >;

  getPlacement: TypedContractMethod<
    [_studentEnrollment: string, _jobListingId: string],
    [[string, string, bigint, boolean]],
    "view"
  >;

  jobListings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, boolean] & {
        id: bigint;
        institutionalId: string;
        jobTitle: string;
        companyName: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  nextJobId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  placementOffers: TypedContractMethod<
    [arg0: string, arg1: string],
    [
      [string, string, string, bigint, boolean] & {
        studentEnrollment: string;
        jobListingId: string;
        offerHash: string;
        timestamp: bigint;
        isAccepted: boolean;
      }
    ],
    "view"
  >;

  postJob: TypedContractMethod<
    [_institutionalId: string, _jobTitle: string, _companyName: string],
    [void],
    "nonpayable"
  >;

  recordPlacement: TypedContractMethod<
    [_studentEnrollment: string, _jobListingId: string, _offerHash: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  toggleJobStatus: TypedContractMethod<
    [_jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOffer"
  ): TypedContractMethod<
    [_studentEnrollment: string, _jobListingId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPlacement"
  ): TypedContractMethod<
    [_studentEnrollment: string, _jobListingId: string],
    [[string, string, bigint, boolean]],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobListings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, boolean] & {
        id: bigint;
        institutionalId: string;
        jobTitle: string;
        companyName: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextJobId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placementOffers"
  ): TypedContractMethod<
    [arg0: string, arg1: string],
    [
      [string, string, string, bigint, boolean] & {
        studentEnrollment: string;
        jobListingId: string;
        offerHash: string;
        timestamp: bigint;
        isAccepted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "postJob"
  ): TypedContractMethod<
    [_institutionalId: string, _jobTitle: string, _companyName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordPlacement"
  ): TypedContractMethod<
    [_studentEnrollment: string, _jobListingId: string, _offerHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toggleJobStatus"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "JobPosted"
  ): TypedContractEvent<
    JobPostedEvent.InputTuple,
    JobPostedEvent.OutputTuple,
    JobPostedEvent.OutputObject
  >;
  getEvent(
    key: "JobStatusChanged"
  ): TypedContractEvent<
    JobStatusChangedEvent.InputTuple,
    JobStatusChangedEvent.OutputTuple,
    JobStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "OfferAccepted"
  ): TypedContractEvent<
    OfferAcceptedEvent.InputTuple,
    OfferAcceptedEvent.OutputTuple,
    OfferAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlacementRecorded"
  ): TypedContractEvent<
    PlacementRecordedEvent.InputTuple,
    PlacementRecordedEvent.OutputTuple,
    PlacementRecordedEvent.OutputObject
  >;

  filters: {
    "JobPosted(uint256,string,string,string)": TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;
    JobPosted: TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;

    "JobStatusChanged(uint256,bool)": TypedContractEvent<
      JobStatusChangedEvent.InputTuple,
      JobStatusChangedEvent.OutputTuple,
      JobStatusChangedEvent.OutputObject
    >;
    JobStatusChanged: TypedContractEvent<
      JobStatusChangedEvent.InputTuple,
      JobStatusChangedEvent.OutputTuple,
      JobStatusChangedEvent.OutputObject
    >;

    "OfferAccepted(string,string)": TypedContractEvent<
      OfferAcceptedEvent.InputTuple,
      OfferAcceptedEvent.OutputTuple,
      OfferAcceptedEvent.OutputObject
    >;
    OfferAccepted: TypedContractEvent<
      OfferAcceptedEvent.InputTuple,
      OfferAcceptedEvent.OutputTuple,
      OfferAcceptedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlacementRecorded(string,string,string)": TypedContractEvent<
      PlacementRecordedEvent.InputTuple,
      PlacementRecordedEvent.OutputTuple,
      PlacementRecordedEvent.OutputObject
    >;
    PlacementRecorded: TypedContractEvent<
      PlacementRecordedEvent.InputTuple,
      PlacementRecordedEvent.OutputTuple,
      PlacementRecordedEvent.OutputObject
    >;
  };
}
