/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartCampusEquityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "achieveMilestone"
      | "addMilestone"
      | "owner"
      | "registerStartup"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MilestoneAchieved"
      | "OwnershipTransferred"
      | "StartupRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "achieveMilestone",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addMilestone",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerStartup",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "achieveMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerStartup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MilestoneAchievedEvent {
  export type InputTuple = [
    startupId: string,
    milestoneId: string,
    amountReleased: BigNumberish
  ];
  export type OutputTuple = [
    startupId: string,
    milestoneId: string,
    amountReleased: bigint
  ];
  export interface OutputObject {
    startupId: string;
    milestoneId: string;
    amountReleased: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StartupRegisteredEvent {
  export type InputTuple = [
    startupId: string,
    founder: AddressLike,
    totalEquity: BigNumberish
  ];
  export type OutputTuple = [
    startupId: string,
    founder: string,
    totalEquity: bigint
  ];
  export interface OutputObject {
    startupId: string;
    founder: string;
    totalEquity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartCampusEquity extends BaseContract {
  connect(runner?: ContractRunner | null): SmartCampusEquity;
  waitForDeployment(): Promise<this>;

  interface: SmartCampusEquityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  achieveMilestone: TypedContractMethod<
    [startupId: string, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  addMilestone: TypedContractMethod<
    [
      startupId: string,
      milestoneId: string,
      description: string,
      percentage: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerStartup: TypedContractMethod<
    [startupId: string, founder: AddressLike],
    [void],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "achieveMilestone"
  ): TypedContractMethod<
    [startupId: string, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addMilestone"
  ): TypedContractMethod<
    [
      startupId: string,
      milestoneId: string,
      description: string,
      percentage: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerStartup"
  ): TypedContractMethod<
    [startupId: string, founder: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MilestoneAchieved"
  ): TypedContractEvent<
    MilestoneAchievedEvent.InputTuple,
    MilestoneAchievedEvent.OutputTuple,
    MilestoneAchievedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StartupRegistered"
  ): TypedContractEvent<
    StartupRegisteredEvent.InputTuple,
    StartupRegisteredEvent.OutputTuple,
    StartupRegisteredEvent.OutputObject
  >;

  filters: {
    "MilestoneAchieved(string,string,uint256)": TypedContractEvent<
      MilestoneAchievedEvent.InputTuple,
      MilestoneAchievedEvent.OutputTuple,
      MilestoneAchievedEvent.OutputObject
    >;
    MilestoneAchieved: TypedContractEvent<
      MilestoneAchievedEvent.InputTuple,
      MilestoneAchievedEvent.OutputTuple,
      MilestoneAchievedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StartupRegistered(string,address,uint256)": TypedContractEvent<
      StartupRegisteredEvent.InputTuple,
      StartupRegisteredEvent.OutputTuple,
      StartupRegisteredEvent.OutputObject
    >;
    StartupRegistered: TypedContractEvent<
      StartupRegisteredEvent.InputTuple,
      StartupRegisteredEvent.OutputTuple,
      StartupRegisteredEvent.OutputObject
    >;
  };
}
