/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartCampusComplaintsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "complaints"
      | "owner"
      | "registerComplaint"
      | "renounceOwnership"
      | "resolveComplaint"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComplaintEscalated"
      | "ComplaintRegistered"
      | "ComplaintResolved"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "complaints", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerComplaint",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveComplaint",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "complaints", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ComplaintEscalatedEvent {
  export type InputTuple = [complaintId: string, timestamp: BigNumberish];
  export type OutputTuple = [complaintId: string, timestamp: bigint];
  export interface OutputObject {
    complaintId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintRegisteredEvent {
  export type InputTuple = [
    complaintId: string,
    deadline: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    deadline: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    deadline: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintResolvedEvent {
  export type InputTuple = [complaintId: string, timestamp: BigNumberish];
  export type OutputTuple = [complaintId: string, timestamp: bigint];
  export interface OutputObject {
    complaintId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartCampusComplaints extends BaseContract {
  connect(runner?: ContractRunner | null): SmartCampusComplaints;
  waitForDeployment(): Promise<this>;

  interface: SmartCampusComplaintsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  complaints: TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, bigint, bigint, boolean] & {
        complaintId: string;
        registeredAt: bigint;
        deadline: bigint;
        resolvedAt: bigint;
        isResolved: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerComplaint: TypedContractMethod<
    [complaintId: string, deadline: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveComplaint: TypedContractMethod<
    [complaintId: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "complaints"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, bigint, bigint, boolean] & {
        complaintId: string;
        registeredAt: bigint;
        deadline: bigint;
        resolvedAt: bigint;
        isResolved: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerComplaint"
  ): TypedContractMethod<
    [complaintId: string, deadline: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveComplaint"
  ): TypedContractMethod<[complaintId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ComplaintEscalated"
  ): TypedContractEvent<
    ComplaintEscalatedEvent.InputTuple,
    ComplaintEscalatedEvent.OutputTuple,
    ComplaintEscalatedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintRegistered"
  ): TypedContractEvent<
    ComplaintRegisteredEvent.InputTuple,
    ComplaintRegisteredEvent.OutputTuple,
    ComplaintRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintResolved"
  ): TypedContractEvent<
    ComplaintResolvedEvent.InputTuple,
    ComplaintResolvedEvent.OutputTuple,
    ComplaintResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ComplaintEscalated(string,uint256)": TypedContractEvent<
      ComplaintEscalatedEvent.InputTuple,
      ComplaintEscalatedEvent.OutputTuple,
      ComplaintEscalatedEvent.OutputObject
    >;
    ComplaintEscalated: TypedContractEvent<
      ComplaintEscalatedEvent.InputTuple,
      ComplaintEscalatedEvent.OutputTuple,
      ComplaintEscalatedEvent.OutputObject
    >;

    "ComplaintRegistered(string,uint256,uint256)": TypedContractEvent<
      ComplaintRegisteredEvent.InputTuple,
      ComplaintRegisteredEvent.OutputTuple,
      ComplaintRegisteredEvent.OutputObject
    >;
    ComplaintRegistered: TypedContractEvent<
      ComplaintRegisteredEvent.InputTuple,
      ComplaintRegisteredEvent.OutputTuple,
      ComplaintRegisteredEvent.OutputObject
    >;

    "ComplaintResolved(string,uint256)": TypedContractEvent<
      ComplaintResolvedEvent.InputTuple,
      ComplaintResolvedEvent.OutputTuple,
      ComplaintResolvedEvent.OutputObject
    >;
    ComplaintResolved: TypedContractEvent<
      ComplaintResolvedEvent.InputTuple,
      ComplaintResolvedEvent.OutputTuple,
      ComplaintResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
