/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartCampusGovernanceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "contestPrizePools"
      | "createPoll"
      | "distributePrize"
      | "fundContest"
      | "owner"
      | "patents"
      | "registerIP"
      | "renounceOwnership"
      | "transferOwnership"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PatentRegistered"
      | "PrizeDistributed"
      | "PrizePoolFunded"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "contestPrizePools",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createPoll",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributePrize",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "fundContest", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "patents", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerIP",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "contestPrizePools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPoll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributePrize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundContest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "patents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registerIP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatentRegisteredEvent {
  export type InputTuple = [
    patentId: string,
    owner: AddressLike,
    ipHash: string
  ];
  export type OutputTuple = [patentId: string, owner: string, ipHash: string];
  export interface OutputObject {
    patentId: string;
    owner: string;
    ipHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrizeDistributedEvent {
  export type InputTuple = [
    contestId: string,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [contestId: string, winner: string, amount: bigint];
  export interface OutputObject {
    contestId: string;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrizePoolFundedEvent {
  export type InputTuple = [contestId: string, amount: BigNumberish];
  export type OutputTuple = [contestId: string, amount: bigint];
  export interface OutputObject {
    contestId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    pollId: string,
    voter: AddressLike,
    optionIndex: BigNumberish
  ];
  export type OutputTuple = [
    pollId: string,
    voter: string,
    optionIndex: bigint
  ];
  export interface OutputObject {
    pollId: string;
    voter: string;
    optionIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartCampusGovernance extends BaseContract {
  connect(runner?: ContractRunner | null): SmartCampusGovernance;
  waitForDeployment(): Promise<this>;

  interface: SmartCampusGovernanceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contestPrizePools: TypedContractMethod<[arg0: string], [bigint], "view">;

  createPoll: TypedContractMethod<
    [pollId: string, question: string, duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributePrize: TypedContractMethod<
    [contestId: string, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  fundContest: TypedContractMethod<[contestId: string], [void], "payable">;

  owner: TypedContractMethod<[], [string], "view">;

  patents: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint] & {
        patentId: string;
        ipHash: string;
        owner: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  registerIP: TypedContractMethod<
    [patentId: string, ipHash: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [pollId: string, optionIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contestPrizePools"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPoll"
  ): TypedContractMethod<
    [pollId: string, question: string, duration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributePrize"
  ): TypedContractMethod<
    [contestId: string, winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundContest"
  ): TypedContractMethod<[contestId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "patents"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint] & {
        patentId: string;
        ipHash: string;
        owner: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerIP"
  ): TypedContractMethod<
    [patentId: string, ipHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [pollId: string, optionIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PatentRegistered"
  ): TypedContractEvent<
    PatentRegisteredEvent.InputTuple,
    PatentRegisteredEvent.OutputTuple,
    PatentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PrizeDistributed"
  ): TypedContractEvent<
    PrizeDistributedEvent.InputTuple,
    PrizeDistributedEvent.OutputTuple,
    PrizeDistributedEvent.OutputObject
  >;
  getEvent(
    key: "PrizePoolFunded"
  ): TypedContractEvent<
    PrizePoolFundedEvent.InputTuple,
    PrizePoolFundedEvent.OutputTuple,
    PrizePoolFundedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PatentRegistered(string,address,string)": TypedContractEvent<
      PatentRegisteredEvent.InputTuple,
      PatentRegisteredEvent.OutputTuple,
      PatentRegisteredEvent.OutputObject
    >;
    PatentRegistered: TypedContractEvent<
      PatentRegisteredEvent.InputTuple,
      PatentRegisteredEvent.OutputTuple,
      PatentRegisteredEvent.OutputObject
    >;

    "PrizeDistributed(string,address,uint256)": TypedContractEvent<
      PrizeDistributedEvent.InputTuple,
      PrizeDistributedEvent.OutputTuple,
      PrizeDistributedEvent.OutputObject
    >;
    PrizeDistributed: TypedContractEvent<
      PrizeDistributedEvent.InputTuple,
      PrizeDistributedEvent.OutputTuple,
      PrizeDistributedEvent.OutputObject
    >;

    "PrizePoolFunded(string,uint256)": TypedContractEvent<
      PrizePoolFundedEvent.InputTuple,
      PrizePoolFundedEvent.OutputTuple,
      PrizePoolFundedEvent.OutputObject
    >;
    PrizePoolFunded: TypedContractEvent<
      PrizePoolFundedEvent.InputTuple,
      PrizePoolFundedEvent.OutputTuple,
      PrizePoolFundedEvent.OutputObject
    >;

    "VoteCast(string,address,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
