/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartCampusLibraryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "loans"
      | "owner"
      | "recordLoan"
      | "recordReturn"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BookIssued"
      | "BookReturned"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "loans", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordLoan",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordReturn",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recordLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BookIssuedEvent {
  export type InputTuple = [loanId: string, isbn: string, enrollmentNo: string];
  export type OutputTuple = [
    loanId: string,
    isbn: string,
    enrollmentNo: string
  ];
  export interface OutputObject {
    loanId: string;
    isbn: string;
    enrollmentNo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookReturnedEvent {
  export type InputTuple = [
    loanId: string,
    fineAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    loanId: string,
    fineAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    loanId: string;
    fineAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartCampusLibrary extends BaseContract {
  connect(runner?: ContractRunner | null): SmartCampusLibrary;
  waitForDeployment(): Promise<this>;

  interface: SmartCampusLibraryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  loans: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        loanId: string;
        isbn: string;
        enrollmentNo: string;
        issuedAt: bigint;
        returnedAt: bigint;
        fineAmount: bigint;
        isReturned: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordLoan: TypedContractMethod<
    [loanId: string, isbn: string, enrollmentNo: string],
    [void],
    "nonpayable"
  >;

  recordReturn: TypedContractMethod<
    [loanId: string, fineAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        loanId: string;
        isbn: string;
        enrollmentNo: string;
        issuedAt: bigint;
        returnedAt: bigint;
        fineAmount: bigint;
        isReturned: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordLoan"
  ): TypedContractMethod<
    [loanId: string, isbn: string, enrollmentNo: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordReturn"
  ): TypedContractMethod<
    [loanId: string, fineAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BookIssued"
  ): TypedContractEvent<
    BookIssuedEvent.InputTuple,
    BookIssuedEvent.OutputTuple,
    BookIssuedEvent.OutputObject
  >;
  getEvent(
    key: "BookReturned"
  ): TypedContractEvent<
    BookReturnedEvent.InputTuple,
    BookReturnedEvent.OutputTuple,
    BookReturnedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BookIssued(string,string,string)": TypedContractEvent<
      BookIssuedEvent.InputTuple,
      BookIssuedEvent.OutputTuple,
      BookIssuedEvent.OutputObject
    >;
    BookIssued: TypedContractEvent<
      BookIssuedEvent.InputTuple,
      BookIssuedEvent.OutputTuple,
      BookIssuedEvent.OutputObject
    >;

    "BookReturned(string,uint256,uint256)": TypedContractEvent<
      BookReturnedEvent.InputTuple,
      BookReturnedEvent.OutputTuple,
      BookReturnedEvent.OutputObject
    >;
    BookReturned: TypedContractEvent<
      BookReturnedEvent.InputTuple,
      BookReturnedEvent.OutputTuple,
      BookReturnedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
