/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartCampusLearningInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "fundCoaching"
      | "hasAccess"
      | "owner"
      | "purchaseModule"
      | "releaseCoachingPayment"
      | "renounceOwnership"
      | "sessions"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CoachingFunded"
      | "CoachingPaymentReleased"
      | "ModulePurchased"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "fundCoaching",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseModule",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseCoachingPayment",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sessions", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "fundCoaching",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseCoachingPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sessions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace CoachingFundedEvent {
  export type InputTuple = [
    sessionId: string,
    tutor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [sessionId: string, tutor: string, amount: bigint];
  export interface OutputObject {
    sessionId: string;
    tutor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CoachingPaymentReleasedEvent {
  export type InputTuple = [
    sessionId: string,
    tutor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [sessionId: string, tutor: string, amount: bigint];
  export interface OutputObject {
    sessionId: string;
    tutor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModulePurchasedEvent {
  export type InputTuple = [
    moduleId: string,
    student: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [moduleId: string, student: string, amount: bigint];
  export interface OutputObject {
    moduleId: string;
    student: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartCampusLearning extends BaseContract {
  connect(runner?: ContractRunner | null): SmartCampusLearning;
  waitForDeployment(): Promise<this>;

  interface: SmartCampusLearningInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fundCoaching: TypedContractMethod<
    [sessionId: string, tutor: AddressLike],
    [void],
    "payable"
  >;

  hasAccess: TypedContractMethod<
    [arg0: string, arg1: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  purchaseModule: TypedContractMethod<[moduleId: string], [void], "payable">;

  releaseCoachingPayment: TypedContractMethod<
    [sessionId: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sessions: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        sessionId: string;
        tutor: string;
        fee: bigint;
        isReleased: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fundCoaching"
  ): TypedContractMethod<
    [sessionId: string, tutor: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<[arg0: string, arg1: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseModule"
  ): TypedContractMethod<[moduleId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "releaseCoachingPayment"
  ): TypedContractMethod<[sessionId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sessions"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        sessionId: string;
        tutor: string;
        fee: bigint;
        isReleased: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CoachingFunded"
  ): TypedContractEvent<
    CoachingFundedEvent.InputTuple,
    CoachingFundedEvent.OutputTuple,
    CoachingFundedEvent.OutputObject
  >;
  getEvent(
    key: "CoachingPaymentReleased"
  ): TypedContractEvent<
    CoachingPaymentReleasedEvent.InputTuple,
    CoachingPaymentReleasedEvent.OutputTuple,
    CoachingPaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "ModulePurchased"
  ): TypedContractEvent<
    ModulePurchasedEvent.InputTuple,
    ModulePurchasedEvent.OutputTuple,
    ModulePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CoachingFunded(string,address,uint256)": TypedContractEvent<
      CoachingFundedEvent.InputTuple,
      CoachingFundedEvent.OutputTuple,
      CoachingFundedEvent.OutputObject
    >;
    CoachingFunded: TypedContractEvent<
      CoachingFundedEvent.InputTuple,
      CoachingFundedEvent.OutputTuple,
      CoachingFundedEvent.OutputObject
    >;

    "CoachingPaymentReleased(string,address,uint256)": TypedContractEvent<
      CoachingPaymentReleasedEvent.InputTuple,
      CoachingPaymentReleasedEvent.OutputTuple,
      CoachingPaymentReleasedEvent.OutputObject
    >;
    CoachingPaymentReleased: TypedContractEvent<
      CoachingPaymentReleasedEvent.InputTuple,
      CoachingPaymentReleasedEvent.OutputTuple,
      CoachingPaymentReleasedEvent.OutputObject
    >;

    "ModulePurchased(string,address,uint256)": TypedContractEvent<
      ModulePurchasedEvent.InputTuple,
      ModulePurchasedEvent.OutputTuple,
      ModulePurchasedEvent.OutputObject
    >;
    ModulePurchased: TypedContractEvent<
      ModulePurchasedEvent.InputTuple,
      ModulePurchasedEvent.OutputTuple,
      ModulePurchasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
