/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartCampusFinanceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "feeHistory"
      | "getFeeHistoryCount"
      | "getFeeReceipt"
      | "owner"
      | "payrollHistory"
      | "recordFeePayment"
      | "recordPayroll"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeePaymentRecorded"
      | "OwnershipTransferred"
      | "PayrollDisbursed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "feeHistory",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeHistoryCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeReceipt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payrollHistory",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordFeePayment",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPayroll",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "feeHistory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFeeHistoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payrollHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordFeePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPayroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace FeePaymentRecordedEvent {
  export type InputTuple = [
    studentEnrollment: string,
    feeType: string,
    amount: BigNumberish,
    transactionId: string
  ];
  export type OutputTuple = [
    studentEnrollment: string,
    feeType: string,
    amount: bigint,
    transactionId: string
  ];
  export interface OutputObject {
    studentEnrollment: string;
    feeType: string;
    amount: bigint;
    transactionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayrollDisbursedEvent {
  export type InputTuple = [
    employeeId: string,
    monthYear: string,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    employeeId: string,
    monthYear: string,
    amount: bigint
  ];
  export interface OutputObject {
    employeeId: string;
    monthYear: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartCampusFinance extends BaseContract {
  connect(runner?: ContractRunner | null): SmartCampusFinance;
  waitForDeployment(): Promise<this>;

  interface: SmartCampusFinanceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  feeHistory: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, string, bigint, string, bigint] & {
        studentEnrollment: string;
        feeType: string;
        amount: bigint;
        transactionId: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFeeHistoryCount: TypedContractMethod<
    [_studentEnrollment: string],
    [bigint],
    "view"
  >;

  getFeeReceipt: TypedContractMethod<
    [_studentEnrollment: string, _index: BigNumberish],
    [[string, bigint, string, bigint]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payrollHistory: TypedContractMethod<
    [arg0: string, arg1: string],
    [
      [string, string, bigint, string, bigint] & {
        employeeId: string;
        monthYear: string;
        amount: bigint;
        status: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  recordFeePayment: TypedContractMethod<
    [
      _studentEnrollment: string,
      _feeType: string,
      _amount: BigNumberish,
      _transactionId: string
    ],
    [void],
    "nonpayable"
  >;

  recordPayroll: TypedContractMethod<
    [_employeeId: string, _monthYear: string, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "feeHistory"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, string, bigint, string, bigint] & {
        studentEnrollment: string;
        feeType: string;
        amount: bigint;
        transactionId: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeeHistoryCount"
  ): TypedContractMethod<[_studentEnrollment: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFeeReceipt"
  ): TypedContractMethod<
    [_studentEnrollment: string, _index: BigNumberish],
    [[string, bigint, string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payrollHistory"
  ): TypedContractMethod<
    [arg0: string, arg1: string],
    [
      [string, string, bigint, string, bigint] & {
        employeeId: string;
        monthYear: string;
        amount: bigint;
        status: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordFeePayment"
  ): TypedContractMethod<
    [
      _studentEnrollment: string,
      _feeType: string,
      _amount: BigNumberish,
      _transactionId: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordPayroll"
  ): TypedContractMethod<
    [_employeeId: string, _monthYear: string, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FeePaymentRecorded"
  ): TypedContractEvent<
    FeePaymentRecordedEvent.InputTuple,
    FeePaymentRecordedEvent.OutputTuple,
    FeePaymentRecordedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayrollDisbursed"
  ): TypedContractEvent<
    PayrollDisbursedEvent.InputTuple,
    PayrollDisbursedEvent.OutputTuple,
    PayrollDisbursedEvent.OutputObject
  >;

  filters: {
    "FeePaymentRecorded(string,string,uint256,string)": TypedContractEvent<
      FeePaymentRecordedEvent.InputTuple,
      FeePaymentRecordedEvent.OutputTuple,
      FeePaymentRecordedEvent.OutputObject
    >;
    FeePaymentRecorded: TypedContractEvent<
      FeePaymentRecordedEvent.InputTuple,
      FeePaymentRecordedEvent.OutputTuple,
      FeePaymentRecordedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayrollDisbursed(string,string,uint256)": TypedContractEvent<
      PayrollDisbursedEvent.InputTuple,
      PayrollDisbursedEvent.OutputTuple,
      PayrollDisbursedEvent.OutputObject
    >;
    PayrollDisbursed: TypedContractEvent<
      PayrollDisbursedEvent.InputTuple,
      PayrollDisbursedEvent.OutputTuple,
      PayrollDisbursedEvent.OutputObject
    >;
  };
}
