/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartCampusCampusLifeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimLostItem"
      | "events"
      | "fundEvent"
      | "lostItems"
      | "owner"
      | "payHostelRent"
      | "registerLostItem"
      | "releaseEventPayment"
      | "renounceOwnership"
      | "transferOwnership"
      | "withdrawHostelFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EventFunded"
      | "EventPaymentReleased"
      | "LostItemRegistered"
      | "OwnershipTransferred"
      | "RewardDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimLostItem",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "events", values: [string]): string;
  encodeFunctionData(
    functionFragment: "fundEvent",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "lostItems", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payHostelRent",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerLostItem",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseEventPayment",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawHostelFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "claimLostItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "events", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fundEvent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lostItems", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payHostelRent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerLostItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseEventPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawHostelFunds",
    data: BytesLike
  ): Result;
}

export namespace EventFundedEvent {
  export type InputTuple = [
    eventId: string,
    vendor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [eventId: string, vendor: string, amount: bigint];
  export interface OutputObject {
    eventId: string;
    vendor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventPaymentReleasedEvent {
  export type InputTuple = [
    eventId: string,
    vendor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [eventId: string, vendor: string, amount: bigint];
  export interface OutputObject {
    eventId: string;
    vendor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LostItemRegisteredEvent {
  export type InputTuple = [
    itemId: string,
    owner: AddressLike,
    reward: BigNumberish
  ];
  export type OutputTuple = [itemId: string, owner: string, reward: bigint];
  export interface OutputObject {
    itemId: string;
    owner: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [
    itemId: string,
    finder: AddressLike,
    reward: BigNumberish
  ];
  export type OutputTuple = [itemId: string, finder: string, reward: bigint];
  export interface OutputObject {
    itemId: string;
    finder: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartCampusCampusLife extends BaseContract {
  connect(runner?: ContractRunner | null): SmartCampusCampusLife;
  waitForDeployment(): Promise<this>;

  interface: SmartCampusCampusLifeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimLostItem: TypedContractMethod<
    [itemId: string, finder: AddressLike],
    [void],
    "nonpayable"
  >;

  events: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        eventId: string;
        vendor: string;
        amount: bigint;
        isReleased: boolean;
      }
    ],
    "view"
  >;

  fundEvent: TypedContractMethod<
    [eventId: string, vendor: AddressLike],
    [void],
    "payable"
  >;

  lostItems: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean, string] & {
        itemId: string;
        owner: string;
        reward: bigint;
        isFound: boolean;
        finder: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payHostelRent: TypedContractMethod<[enrollmentNo: string], [void], "payable">;

  registerLostItem: TypedContractMethod<[itemId: string], [void], "payable">;

  releaseEventPayment: TypedContractMethod<
    [eventId: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawHostelFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimLostItem"
  ): TypedContractMethod<
    [itemId: string, finder: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "events"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        eventId: string;
        vendor: string;
        amount: bigint;
        isReleased: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundEvent"
  ): TypedContractMethod<
    [eventId: string, vendor: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "lostItems"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean, string] & {
        itemId: string;
        owner: string;
        reward: bigint;
        isFound: boolean;
        finder: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payHostelRent"
  ): TypedContractMethod<[enrollmentNo: string], [void], "payable">;
  getFunction(
    nameOrSignature: "registerLostItem"
  ): TypedContractMethod<[itemId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "releaseEventPayment"
  ): TypedContractMethod<[eventId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawHostelFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "EventFunded"
  ): TypedContractEvent<
    EventFundedEvent.InputTuple,
    EventFundedEvent.OutputTuple,
    EventFundedEvent.OutputObject
  >;
  getEvent(
    key: "EventPaymentReleased"
  ): TypedContractEvent<
    EventPaymentReleasedEvent.InputTuple,
    EventPaymentReleasedEvent.OutputTuple,
    EventPaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "LostItemRegistered"
  ): TypedContractEvent<
    LostItemRegisteredEvent.InputTuple,
    LostItemRegisteredEvent.OutputTuple,
    LostItemRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;

  filters: {
    "EventFunded(string,address,uint256)": TypedContractEvent<
      EventFundedEvent.InputTuple,
      EventFundedEvent.OutputTuple,
      EventFundedEvent.OutputObject
    >;
    EventFunded: TypedContractEvent<
      EventFundedEvent.InputTuple,
      EventFundedEvent.OutputTuple,
      EventFundedEvent.OutputObject
    >;

    "EventPaymentReleased(string,address,uint256)": TypedContractEvent<
      EventPaymentReleasedEvent.InputTuple,
      EventPaymentReleasedEvent.OutputTuple,
      EventPaymentReleasedEvent.OutputObject
    >;
    EventPaymentReleased: TypedContractEvent<
      EventPaymentReleasedEvent.InputTuple,
      EventPaymentReleasedEvent.OutputTuple,
      EventPaymentReleasedEvent.OutputObject
    >;

    "LostItemRegistered(string,address,uint256)": TypedContractEvent<
      LostItemRegisteredEvent.InputTuple,
      LostItemRegisteredEvent.OutputTuple,
      LostItemRegisteredEvent.OutputObject
    >;
    LostItemRegistered: TypedContractEvent<
      LostItemRegisteredEvent.InputTuple,
      LostItemRegisteredEvent.OutputTuple,
      LostItemRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardDistributed(string,address,uint256)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
  };
}
