/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartCampusAcademicPlusInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createScholarship"
      | "distributeScholarship"
      | "examPapers"
      | "getExamPaper"
      | "owner"
      | "registerExamPaper"
      | "renounceOwnership"
      | "scholarshipReceived"
      | "scholarships"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExamPaperRegistered"
      | "OwnershipTransferred"
      | "ScholarshipCreated"
      | "ScholarshipDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createScholarship",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeScholarship",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "examPapers", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getExamPaper",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerExamPaper",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scholarshipReceived",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "scholarships",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createScholarship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeScholarship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "examPapers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getExamPaper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerExamPaper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scholarshipReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scholarships",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ExamPaperRegisteredEvent {
  export type InputTuple = [examId: string, releaseTime: BigNumberish];
  export type OutputTuple = [examId: string, releaseTime: bigint];
  export interface OutputObject {
    examId: string;
    releaseTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScholarshipCreatedEvent {
  export type InputTuple = [scholarshipId: string, totalFund: BigNumberish];
  export type OutputTuple = [scholarshipId: string, totalFund: bigint];
  export interface OutputObject {
    scholarshipId: string;
    totalFund: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScholarshipDistributedEvent {
  export type InputTuple = [
    scholarshipId: string,
    student: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    scholarshipId: string,
    student: string,
    amount: bigint
  ];
  export interface OutputObject {
    scholarshipId: string;
    student: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartCampusAcademicPlus extends BaseContract {
  connect(runner?: ContractRunner | null): SmartCampusAcademicPlus;
  waitForDeployment(): Promise<this>;

  interface: SmartCampusAcademicPlusInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createScholarship: TypedContractMethod<
    [scholarshipId: string, amountPerStudent: BigNumberish],
    [void],
    "payable"
  >;

  distributeScholarship: TypedContractMethod<
    [scholarshipId: string, student: AddressLike],
    [void],
    "nonpayable"
  >;

  examPapers: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        examId: string;
        paperHash: string;
        releaseTime: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getExamPaper: TypedContractMethod<[examId: string], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerExamPaper: TypedContractMethod<
    [examId: string, paperHash: string, releaseTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  scholarshipReceived: TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [boolean],
    "view"
  >;

  scholarships: TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, bigint, boolean] & {
        scholarshipId: string;
        totalFund: bigint;
        amountPerStudent: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createScholarship"
  ): TypedContractMethod<
    [scholarshipId: string, amountPerStudent: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "distributeScholarship"
  ): TypedContractMethod<
    [scholarshipId: string, student: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "examPapers"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        examId: string;
        paperHash: string;
        releaseTime: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getExamPaper"
  ): TypedContractMethod<[examId: string], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerExamPaper"
  ): TypedContractMethod<
    [examId: string, paperHash: string, releaseTime: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scholarshipReceived"
  ): TypedContractMethod<[arg0: AddressLike, arg1: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "scholarships"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, bigint, boolean] & {
        scholarshipId: string;
        totalFund: bigint;
        amountPerStudent: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ExamPaperRegistered"
  ): TypedContractEvent<
    ExamPaperRegisteredEvent.InputTuple,
    ExamPaperRegisteredEvent.OutputTuple,
    ExamPaperRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ScholarshipCreated"
  ): TypedContractEvent<
    ScholarshipCreatedEvent.InputTuple,
    ScholarshipCreatedEvent.OutputTuple,
    ScholarshipCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ScholarshipDistributed"
  ): TypedContractEvent<
    ScholarshipDistributedEvent.InputTuple,
    ScholarshipDistributedEvent.OutputTuple,
    ScholarshipDistributedEvent.OutputObject
  >;

  filters: {
    "ExamPaperRegistered(string,uint256)": TypedContractEvent<
      ExamPaperRegisteredEvent.InputTuple,
      ExamPaperRegisteredEvent.OutputTuple,
      ExamPaperRegisteredEvent.OutputObject
    >;
    ExamPaperRegistered: TypedContractEvent<
      ExamPaperRegisteredEvent.InputTuple,
      ExamPaperRegisteredEvent.OutputTuple,
      ExamPaperRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ScholarshipCreated(string,uint256)": TypedContractEvent<
      ScholarshipCreatedEvent.InputTuple,
      ScholarshipCreatedEvent.OutputTuple,
      ScholarshipCreatedEvent.OutputObject
    >;
    ScholarshipCreated: TypedContractEvent<
      ScholarshipCreatedEvent.InputTuple,
      ScholarshipCreatedEvent.OutputTuple,
      ScholarshipCreatedEvent.OutputObject
    >;

    "ScholarshipDistributed(string,address,uint256)": TypedContractEvent<
      ScholarshipDistributedEvent.InputTuple,
      ScholarshipDistributedEvent.OutputTuple,
      ScholarshipDistributedEvent.OutputObject
    >;
    ScholarshipDistributed: TypedContractEvent<
      ScholarshipDistributedEvent.InputTuple,
      ScholarshipDistributedEvent.OutputTuple,
      ScholarshipDistributedEvent.OutputObject
    >;
  };
}
