/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartCampusReevaluationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "applyForReevaluation"
      | "owner"
      | "renounceOwnership"
      | "requests"
      | "resolveReevaluation"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ReevaluationApplied"
      | "ReevaluationResolved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "applyForReevaluation",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "requests", values: [string]): string;
  encodeFunctionData(
    functionFragment: "resolveReevaluation",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "applyForReevaluation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveReevaluation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReevaluationAppliedEvent {
  export type InputTuple = [
    requestId: string,
    student: AddressLike,
    fee: BigNumberish
  ];
  export type OutputTuple = [requestId: string, student: string, fee: bigint];
  export interface OutputObject {
    requestId: string;
    student: string;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReevaluationResolvedEvent {
  export type InputTuple = [
    requestId: string,
    refunded: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    refunded: boolean,
    amount: bigint
  ];
  export interface OutputObject {
    requestId: string;
    refunded: boolean;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartCampusReevaluation extends BaseContract {
  connect(runner?: ContractRunner | null): SmartCampusReevaluation;
  waitForDeployment(): Promise<this>;

  interface: SmartCampusReevaluationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applyForReevaluation: TypedContractMethod<
    [requestId: string],
    [void],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requests: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean, boolean, bigint] & {
        requestId: string;
        student: string;
        fee: bigint;
        resolved: boolean;
        refunded: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  resolveReevaluation: TypedContractMethod<
    [requestId: string, shouldRefund: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applyForReevaluation"
  ): TypedContractMethod<[requestId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean, boolean, bigint] & {
        requestId: string;
        student: string;
        fee: bigint;
        resolved: boolean;
        refunded: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "resolveReevaluation"
  ): TypedContractMethod<
    [requestId: string, shouldRefund: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReevaluationApplied"
  ): TypedContractEvent<
    ReevaluationAppliedEvent.InputTuple,
    ReevaluationAppliedEvent.OutputTuple,
    ReevaluationAppliedEvent.OutputObject
  >;
  getEvent(
    key: "ReevaluationResolved"
  ): TypedContractEvent<
    ReevaluationResolvedEvent.InputTuple,
    ReevaluationResolvedEvent.OutputTuple,
    ReevaluationResolvedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReevaluationApplied(string,address,uint256)": TypedContractEvent<
      ReevaluationAppliedEvent.InputTuple,
      ReevaluationAppliedEvent.OutputTuple,
      ReevaluationAppliedEvent.OutputObject
    >;
    ReevaluationApplied: TypedContractEvent<
      ReevaluationAppliedEvent.InputTuple,
      ReevaluationAppliedEvent.OutputTuple,
      ReevaluationAppliedEvent.OutputObject
    >;

    "ReevaluationResolved(string,bool,uint256)": TypedContractEvent<
      ReevaluationResolvedEvent.InputTuple,
      ReevaluationResolvedEvent.OutputTuple,
      ReevaluationResolvedEvent.OutputObject
    >;
    ReevaluationResolved: TypedContractEvent<
      ReevaluationResolvedEvent.InputTuple,
      ReevaluationResolvedEvent.OutputTuple,
      ReevaluationResolvedEvent.OutputObject
    >;
  };
}
