/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartCampusAdmissionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admissions"
      | "getAdmissionRecord"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateAdmissionStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AdmissionStatusUpdated" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admissions", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAdmissionRecord",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAdmissionStatus",
    values: [string, string, string, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "admissions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAdmissionRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAdmissionStatus",
    data: BytesLike
  ): Result;
}

export namespace AdmissionStatusUpdatedEvent {
  export type InputTuple = [
    applicationId: string,
    status: BigNumberish,
    documentHash: string
  ];
  export type OutputTuple = [
    applicationId: string,
    status: bigint,
    documentHash: string
  ];
  export interface OutputObject {
    applicationId: string;
    status: bigint;
    documentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartCampusAdmission extends BaseContract {
  connect(runner?: ContractRunner | null): SmartCampusAdmission;
  waitForDeployment(): Promise<this>;

  interface: SmartCampusAdmissionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admissions: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, bigint] & {
        studentEnrollment: string;
        programId: string;
        status: bigint;
        documentHash: string;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;

  getAdmissionRecord: TypedContractMethod<
    [_applicationId: string],
    [[string, string, bigint, string, bigint]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAdmissionStatus: TypedContractMethod<
    [
      _applicationId: string,
      _studentEnrollment: string,
      _programId: string,
      _status: BigNumberish,
      _documentHash: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admissions"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, bigint] & {
        studentEnrollment: string;
        programId: string;
        status: bigint;
        documentHash: string;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAdmissionRecord"
  ): TypedContractMethod<
    [_applicationId: string],
    [[string, string, bigint, string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAdmissionStatus"
  ): TypedContractMethod<
    [
      _applicationId: string,
      _studentEnrollment: string,
      _programId: string,
      _status: BigNumberish,
      _documentHash: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdmissionStatusUpdated"
  ): TypedContractEvent<
    AdmissionStatusUpdatedEvent.InputTuple,
    AdmissionStatusUpdatedEvent.OutputTuple,
    AdmissionStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AdmissionStatusUpdated(string,uint8,string)": TypedContractEvent<
      AdmissionStatusUpdatedEvent.InputTuple,
      AdmissionStatusUpdatedEvent.OutputTuple,
      AdmissionStatusUpdatedEvent.OutputObject
    >;
    AdmissionStatusUpdated: TypedContractEvent<
      AdmissionStatusUpdatedEvent.InputTuple,
      AdmissionStatusUpdatedEvent.OutputTuple,
      AdmissionStatusUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
