/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SmartCampusVerifyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getApplicationStatus"
      | "getStudentRecord"
      | "owner"
      | "publishResult"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateApplicationStatus"
      | "verifyResult"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ResultPublished"
      | "StatusUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getApplicationStatus",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentRecord",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publishResult",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateApplicationStatus",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyResult",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getApplicationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudentRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publishResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateApplicationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyResult",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultPublishedEvent {
  export type InputTuple = [
    enrollmentNo: string,
    resultHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    enrollmentNo: string,
    resultHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    enrollmentNo: string;
    resultHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusUpdatedEvent {
  export type InputTuple = [
    enrollmentNo: string,
    status: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    enrollmentNo: string,
    status: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    enrollmentNo: string;
    status: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartCampusVerify extends BaseContract {
  connect(runner?: ContractRunner | null): SmartCampusVerify;
  waitForDeployment(): Promise<this>;

  interface: SmartCampusVerifyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getApplicationStatus: TypedContractMethod<
    [enrollmentNo: string],
    [string],
    "view"
  >;

  getStudentRecord: TypedContractMethod<
    [enrollmentNo: string],
    [[string, string, bigint]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  publishResult: TypedContractMethod<
    [enrollmentNo: string, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateApplicationStatus: TypedContractMethod<
    [enrollmentNo: string, status: string],
    [void],
    "nonpayable"
  >;

  verifyResult: TypedContractMethod<
    [enrollmentNo: string, resultHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getApplicationStatus"
  ): TypedContractMethod<[enrollmentNo: string], [string], "view">;
  getFunction(
    nameOrSignature: "getStudentRecord"
  ): TypedContractMethod<
    [enrollmentNo: string],
    [[string, string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publishResult"
  ): TypedContractMethod<
    [enrollmentNo: string, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateApplicationStatus"
  ): TypedContractMethod<
    [enrollmentNo: string, status: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyResult"
  ): TypedContractMethod<
    [enrollmentNo: string, resultHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ResultPublished"
  ): TypedContractEvent<
    ResultPublishedEvent.InputTuple,
    ResultPublishedEvent.OutputTuple,
    ResultPublishedEvent.OutputObject
  >;
  getEvent(
    key: "StatusUpdated"
  ): TypedContractEvent<
    StatusUpdatedEvent.InputTuple,
    StatusUpdatedEvent.OutputTuple,
    StatusUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ResultPublished(string,bytes32,uint256)": TypedContractEvent<
      ResultPublishedEvent.InputTuple,
      ResultPublishedEvent.OutputTuple,
      ResultPublishedEvent.OutputObject
    >;
    ResultPublished: TypedContractEvent<
      ResultPublishedEvent.InputTuple,
      ResultPublishedEvent.OutputTuple,
      ResultPublishedEvent.OutputObject
    >;

    "StatusUpdated(string,string,uint256)": TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
    StatusUpdated: TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
  };
}
